version: "3"
services:
  backend:
    build: .
    ports:
      - "4000:4000"
    environment:
      - GHTOKEN=${GHTOKEN}
      - AUTHORS=${AUTHORS}
      - BOZZ=${BOZZ}
      - REFRESH_INTERVAL=${REFRESH_INTERVAL}
