version: "3"
services:
  backend:
    build: .
    ports:
      - "4000:4000"
    environment:
      - GHTOKEN=${GHTOKEN}
      - AUTHORS=${AUTHORS}
      - REQUIRED_PR_COUNT=${REQUIRED_PR_COUNT}
      - REFRESH_INTERVAL=${REFRESH_INTERVAL:-1800}
      - BOZZ=${BOZZ}
      - TIMEZONE=${TIMEZONE}
